services:
  - type: web
    name: yazithsafi
    plan: free
    runtime: php
    region: oregon
    env: production
    buildCommand: |
      cp .env.example .env &&
      php artisan key:generate &&
      composer install
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://6sifat.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_DATABASE
        value: apps
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: Haaland@9